### ISSUE TITLE
新建大屏无标签选项却一直提示【请选择标签】且无法保存

### ISSUE THREAD

**Issue by Rosso-Wang** [CloudWise-OpenSource/FlyFish#1]
![image](https://user-images.githubusercontent.com/59380115/138680379-31ef54ec-851e-46d8-99a1-8f7421137bda.png)

**Comment by xiaohu12685** [comment]
已修复，已合并到Master分支。 
commit记录为：2554e6dc210401d04531404a86cce6cba8b9dabc
