### ISSUE TITLE
组件开发这块报错,连不上服务端

### ISSUE THREAD

**Issue by Markuuuu** [CloudWise-OpenSource/FlyFish#106]
组件开发这块报错,连不上服务端,还报缺少文件，我看了目录下面，确实没有这个文件

![image (2)](https://user-images.githubusercontent.com/52529445/168072179-d8ec034b-78a2-4a88-9090-2a8281880a74.png)

**Comment by xiaohu12685** [comment]
组件包未导入，组件包下载地址
 https://flyfish-demo.opscloudwise.com:23332/commonComponentDownload
