### ISSUE TITLE
介绍视频是否能更新下，版本对不

### ISSUE THREAD

**Issue by Markuuuu** [CloudWise-OpenSource/FlyFish#107]
那个bilibili的视频基本没用，不知道你们视频里面的版本是gitee上的版本，介绍视频是否能更新下，版本对不

**Comment by YouYe** [comment]
针对组件开发和可视化大屏开发等，应该无变化，对于操作上和安装上的不同，暂时未推出视频，相关文档已更新，请先查阅文档，如文档也解决不了您的问题，请及时反馈

**Comment by RiseHao1029** [comment]
这个是新版的安装视频教程： https://www.bilibili.com/video/BV1tA4y1o7G6/?vd_source=6463603beba710beac42aab93b1b4dea
