### ISSUE TITLE
组件开发平台拖入组件报错

### ISSUE THREAD

**Issue by Markuuuu** [CloudWise-OpenSource/FlyFish#108]
![image (3)](https://user-images.githubusercontent.com/52529445/168072832-6332911d-c262-46b1-a5b0-223371879da8.png)
![image (4)](https://user-images.githubusercontent.com/52529445/168072846-f72cb18e-c47c-4591-9fbe-6bb8ec956adb.png)

**Comment by xiaohu12685** [comment]
导入的组件有问题，可以从仓库中下载
https://github.com/CloudWise-OpenSource/FlyFishComponents
