### ISSUE TITLE
公共组件导出之后重新导入报错

### ISSUE THREAD

**Issue by Markuuuu** [CloudWise-OpenSource/FlyFish#110]
我安装配置的flyfish2.0的版本，发现公共组件是没有的，先在线导出，再导入进去无法正常显示？
是我配置的架构有问题？我用的mysql，redis，code-server，solution_platform，visual_component_platform都是单独用dokcer做的镜像在k8s上运行的
<img width="959" alt="image (6)" src="https://user-images.githubusercontent.com/52529445/168073777-efb6dc0f-e88b-48b7-b300-1321f64e4365.png">

**Comment by xiaohu12685** [comment]
导出的并非是公共组件，可以在仓库中下载：https://github.com/CloudWise-OpenSource/FlyFishComponents
