### ISSUE TITLE
文档比较复杂，找不到执行命令的目录，建议将执行命令的目录放进去

### ISSUE THREAD

**Issue by Markuuuu** [CloudWise-OpenSource/FlyFish#116]
文档比较复杂，找不到执行命令的目录，建议将执行命令的目录放进去，方便直接拷贝

**Comment by Neeke** [comment]
可使用readme中的一键脚本

# CentOS 7.5/7.6  x86-64
# 须使用root账户
mkdir -p /data/app/
cd /data/app/

git clone -b main https://github.com/CloudWise-OpenSource/FlyFish.git FlyFish
or
git clone -b main https://gitee.com/CloudWise/fly-fish.git FlyFish

cd /data/app/FlyFish
bash flyfish.sh install

# 一键卸载
bash flyfish.sh uninstall

# 一键更新
# FlyFish-2.1.1 升级至 FlyFish-2.1.2
git checkout main
git pull origin main

bash flyfish.sh update

**Comment by soulferryman** [comment]
@all-contributors please add @Markuuuu  for Code

**Comment by soulferryman** [comment]
@all-contributors please add @osramywj for ideas

**Comment by soulferryman** [comment]
@all-contributors please add @xiaohu12685 for fundingFinding
