### ISSUE TITLE
安装完项目可否内置一些demo示例数据

### ISSUE THREAD

**Issue by jimmy201602** [CloudWise-OpenSource/FlyFish#120]
安装完成此项目后，是否可以内置一些初始化的demo示例数据，以便大家更好的使用学习此项目

**Comment by jincheny** [comment]
FlyFish社区同样开源了一批公共组件供开发者免费使用，但是需要用户手动导入到私有化部署的FlyFish中。
FlyFish后期版本中会在一键部署脚本中添加自动化导入开源组件的功能。
**FlyFish公共组件库：**[FlyFishComponents](https://github.com/CloudWise-OpenSource/FlyFishComponents)
