### ISSUE TITLE
使用vscode remote-ssh时部署codeServer的问题

### ISSUE THREAD

**Issue by faga1** [CloudWise-OpenSource/FlyFish#125]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。**

- [x] 已阅读 [开发文档](http://docs.aiops.cloudwise.com/zh/flyfish/)、[01-基础环境准备篇](../../doc/01-%E5%9F%BA%E7%A1%80%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87%E7%AF%87.md)、[02-FlyFish 平台部署篇](../../doc/02-FlyFish%E5%B9%B3%E5%8F%B0%E9%83%A8%E7%BD%B2%E7%AF%87.md)、[03-code_server 部署篇](../../doc/03-code_server%E9%83%A8%E7%BD%B2%E7%AF%87.md)。
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现。
- [x] 已在 Issues 中搜索了相关的关键词

### 描述 Bug
在使用vscode remote-ssh插件时部署codeServer不成功

### 复现 Bug
npm run linux-start
pm2 报错
error Please specify at least one file or folder

使用正常的ssh连接进行部署即可

## 系统信息

- 操作系统: CentOS7.6(默认)
- Node 版本: NodeJS14.9(默认)

**Comment by jincheny** [comment]
**问题描述**
pm2 启动失败，一直重启。
pm2 log code-server 查看日志提示：error Please specify at least one file or folder

**解决方案：**
code-server 官方issue中有同样的反馈：
[code-server issue](https://github.com/coder/code-server/issues/2827)
使用其他 ssh 工具连接服务器即可，如：Iterm2、Xshell
