### ISSUE TITLE
README 英文翻译

### ISSUE THREAD

**Issue by Rosso-Wang** [CloudWise-OpenSource/FlyFish#134]
将 [README.md](https://github.com/CloudWise-OpenSource/FlyFish#readme) 翻译成英文

**Comment by Xlight5** [comment]
FlyFish
   
see the code
FlyFish is a data visualization coding platform. Quickly create data models in an easy way, and quickly generate a set of data visualization solutions by dragging and dropping.
Overview of FlyFish features
Project management: Projects are used to represent specific business demand scenarios and are a collection of multiple applications and components.
Application development: support the development of large-screen applications, and can develop large-screen applications with single-page or multi-page routing.
Component development: Components are the project foundation with the smallest granularity. By creating and developing components, the final visual large-screen display is pieced together.
Template library: The developed applications/components can be uploaded to the corresponding template library, and new projects can be quickly created on the basis of existing templates.
Data source management: It can access multiple database data such as MySQL and Http to generate corresponding data sources for components to call data when creating projects.
Data query: It supports SQL query according to the data table, accurately locates the specific data in the data source and encapsulates and saves it, and can also recombine the queried data for direct call by the component.
FlyFish Template Center
Template Center
Source code download
Get started quickly
Domestic mirror : https://gitee.com/CloudWise/fly-fish
Demo environment address : https://flyfish-demo.opscloudwise.com:23368
local deployment
Occupied port
deskport
FlyfishWeb port (nginx static resource proxy) 8089 
FlyfishCodeServer (online editor) port 8081 
FlyfishServer (main backend service) port 7001 
FlyfishDataServer (data source management service) port 18532 
Deployment process
It is recommended to use the flyfish deployment documents in the doc directory, and the subsequent deployment process, learning materials, FAQs, etc., are placed in the doc directory for management.
01-Basic environment preparation
02-code_server deployment a

**Comment by jincheny** [comment]
@Xlight5  英文文档内容滞后了……
