### ISSUE TITLE
修复FlyFish项目问题并提交PR

### ISSUE THREAD

**Issue by Rosso-Wang** [CloudWise-OpenSource/FlyFish#136]
通过以下任意一种形式使用FlyFish发现其Bug，修复并提交PR

使用方式一：[线上Demo环境体验](https://flyfish-demo.opscloudwise.com:23368/#/login)
使用方式二：[本地下载部署使用](https://github.com/CloudWise-OpenSource/FlyFish)

**Comment by soulferryman** [comment]
@all-contributors please add @sssssssugar for code
