### ISSUE TITLE
组件模板源码导入后保证在项目里能正常展示和使用

### ISSUE THREAD

**Issue by xiaocaimeng007** [CloudWise-OpenSource/FlyFish#144]
### 问题

组件模板源码导入后，在项目中无法正常展示，无法正常使用，需要修改组件模板的相关文件，才能正常使用。
### 预期
1、提供组件模板自动导入功能：比如基础组件在一键部署阶段就已经实现了导入。
2、提供需要修改组件模板相关文件的修改示例，或者相关讲解。

**Comment by jincheny** [comment]
@xiaocaimeng007 

[FlyFish-2.2.0导入FlyFishComponents组件后报错不可用解决方法Q11](https://github.com/CloudWise-OpenSource/FlyFish/discussions/137#discussion-4218275)
