### ISSUE TITLE
组件保存和应用发布后，预览图的展示状态会有延迟，不是立即展示最新的

### ISSUE THREAD

**Issue by xiaocaimeng007** [CloudWise-OpenSource/FlyFish#145]
### 功能描述

组件保存和应用发布后，预览图的展示状态会有延迟，不是立即展示最新的

### 问题

组件保存和应用发布后，预览图的展示状态，刷新后依然不是最新的，需要过一段时间（没有具体测时间，但感觉应该在10Min以上）才会更新为正确的状态

### 预期

组件保存和应用发布后，预览图的展示状态，刷新后立刻变成最新保存的状态
![XQfowUQAFP](https://user-images.githubusercontent.com/30017050/183034053-3ae99ccd-ab6c-4009-9011-6d2157261291.jpg)

**Comment by changlin0501** [comment]
![image](https://user-images.githubusercontent.com/47729295/183043551-d31effc8-fa1a-4d02-84af-0be50b21d0ad.png)
你好，我想请问一下这个图片在哪里设置才显示的吗

**Comment by xiaocaimeng007** [comment]
> 
不是设置的。是应用创建成功，保存后，返回应用列表页，就应该能展示了。但是展示是延时了

**Comment by jincheny** [comment]
@xiaocaimeng007 确实是会有延迟的，FlyFish-2.2.0版本，组件、应用快照生成是通过定时任务生成的（默认10min）。
2.2.0以前版本是保存组件或者应用就会生成快照，但是有严重的性能问题。

**Comment by jincheny** [comment]
@xiaocaimeng007 确实是会有延迟的，FlyFish-2.2.0版本，组件、应用快照生成是通过定时任务生成的（默认10min）。
2.2.0以前版本是保存组件或者应用就会生成快照，但是有严重的性能问题。

**Comment by soulferryman** [comment]
@all-contributors please add @xiaohu12685  for design

**Comment by soulferryman** [comment]
@all-contributors please add @xiaohu12685 for Code

**Comment by soulferryman** [comment]
@all-contributors please add @xiaohu12685 for Code
