### ISSUE TITLE
应用开发中，数据查询下拉数据没有发起请求，导致无法选择已有数据查询

### ISSUE THREAD

**Issue by weiyy2012** [CloudWise-OpenSource/FlyFish#147]
创建数据源，并创建了数据查询，但是在应用开发中，数据查询点击下拉后，数据查询下拉选项为空

**预期**
数据查询点击后，下拉选择为已创建的数据查询数据

**Comment by tpsimon1** [comment]
2.2.1docker部署,也有此问题, 演示环境无此问题

**Comment by jincheny** [comment]
> 2.2.1docker部署,也有此问题, 演示环境无此问题

docker镜像中数据查询接口url未替换，FlyFish-2.2.1 镜像已更新修复该问题。
docker-compose.yaml 目录下执行以下命令可解决您的问题。
`
docker-compose down

docker rmi yunzhihui/flyfishweb:2.2.1

docker-compose up -d
`

**Comment by tpsimon1** [comment]
![image](https://user-images.githubusercontent.com/6112085/191688148-03cbf9a0-a975-4b00-97f7-7a24ce9b0898.png)
![image](https://user-images.githubusercontent.com/6112085/191688282-93567889-b632-46b1-a25d-da4b6cce7f75.png) 
![image](https://user-images.githubusercontent.com/6112085/191688642-82499edd-a8e5-47bc-8dc8-1d6eddae216a.png)
![image](https://user-images.githubusercontent.com/6112085/191688697-a0429724-f37f-4aff-b39b-e9501f8717bb.png)
谷歌浏览器的调试模式里也没有url请求
