### ISSUE TITLE
使用的相关不便之处

### ISSUE THREAD

**Issue by grapecc** [CloudWise-OpenSource/FlyFish#178]
### 功能描述
无
### 问题

项目下的应用，界面左中右 无法用鼠标进行自定义宽度，且直接进入后没有拖拉拽的组件当前操作进度为 创建项目 >> 项目下有应用>>点开应用后 出现页面排版 、黑屏、设置、事件、函数、数据集。默认黑色背景 是否建议默认一张图片？
demo环境下的用户在点开后可以点进来一目了然怎么操作，可以参看一下C# 的winform编译器，只有部分需要使用文档。建议在操作界面，添加链接直达。进入编辑应用页面没法直接 返回需要点后退才能退出

**Comment by jincheny** [comment]
感谢您提出的宝贵建议。我们会汇总社区用户的意见，综合考量您提出的优化建议并参考您说的C# winform编译器的，请您尽请期待。
