### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by gaojidong** [CloudWise-OpenSource/FlyFish#180]
### 功能描述
部署完成后 左侧没有内容，刷新界面会跳转到登录界面，lcapDataServer成功启动。
描述功能
![image](https://user-images.githubusercontent.com/40835761/203786489-0efdb3aa-b660-4c0e-94c2-44789380f517.png)
![image](https://user-images.githubusercontent.com/40835761/203786751-352a026c-abf0-486b-8c97-dd7f9ca81ab4.png)

### 问题

如果功能与问题有关，请在此处描述您是如何解决问题的

### 预期

描述你想要的功能。

**Comment by soulferryman** [comment]
如果是docker部署，可以尝试将docker-compose里的127的地址都改成本机IP后再次尝试

**Comment by jincheny** [comment]
**注意：** 只把flyfishweb的ip修改成服务器IP，如果数据库也修改为服务器IP飞鱼后端服务会连接不上数据库！

![image](https://user-images.githubusercontent.com/54785820/205271689-81e48ef0-7501-4d8d-a3a2-3b192faba47c.png)
