### ISSUE TITLE
使用Docker安装FiyFish v1.0响应时间较长

### ISSUE THREAD

**Issue by Tiper-In-Github** [CloudWise-OpenSource/FlyFish#2]
使用Docker安装FiyFish v1.0时，在安装组件阶段会因为不明原因消耗较长时间，以下为部分控制台信息，卡顿出现在Pull complete 阶段

`[root@VM-8-14-centos FlyFish]# docker build -t flyfish .
Sending build context to Docker daemon  1.379GB
Step 1/7 : FROM luckydwqdocker/flyfish:v1.0
v1.0: Pulling from luckydwqdocker/flyfish
7a0437f04f83: Pull complete 
7d9aacdf270e: Pull complete 
1449949166f9: Pull complete 
939a345cf85c: Pull complete 
3a0d0dbd6603: Pull complete 
Digest: sha256:6322970789d1db9f70d85c62f78bd16a3508a0a7e09cedd9b7fc9a5747457bd2
Status: Downloaded newer image for luckydwqdocker/flyfish:v1.0
 ---> 0f47704824ea
Step 2/7 : WORKDIR /data/app/flyFish/flyfish
 ---> Running in 809ed8081b1e
Removing intermediate container 809ed8081b1e
 ---> e191fcfb8df3
Step 3/7 : COPY . /data/app/flyFish/flyfish
 ---> b9015d3429f9
Step 4/7 : ENV PATH=/root/.nvm/versions/node/v14.17.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 ---> Running in e900b54d3d64
Removing intermediate container e900b54d3d64
 ---> cd0a81c242c1
Step 5/7 : EXPOSE 8364
 ---> Running in 459a329058af
Removing intermediate container 459a329058af
 ---> 5e2aeb2eea51
Step 6/7 : RUN sh startup.sh
 ---> Running in 28b5301ef1d5`

**Comment by Tiper-In-Github** [comment]
实验服务器使用的CentOS 7.9.2009系统，yum、docker版本为最新版

**Comment by maxDwq** [comment]
> 使用Docker安装FiyFish v1.0时，在安装组件阶段会因为不明原因消耗较长时间，以下为部分控制台信息，卡顿出现在Pull complete 阶段
> 
> `[root@VM-8-14-centos FlyFish]# docker build -t flyfish . Sending build context to Docker daemon 1.379GB Step 1/7 : FROM luckydwqdocker/flyfish:v1.0 v1.0: Pulling from luckydwqdocker/flyfish 7a0437f04f83: Pull complete 7d9aacdf270e: Pull complete 1449949166f9: Pull complete 939a345cf85c: Pull complete 3a0d0dbd6603: Pull complete Digest: sha256:6322970789d1db9f70d85c62f78bd16a3508a0a7e09cedd9b7fc9a5747457bd2 Status: Downloaded newer image for luckydwqdocker/flyfish:v1.0 ---> 0f47704824ea Step 2/7 : WORKDIR /data/app/flyFish/flyfish ---> Running in 809ed8081b1e Removing intermediate container 809ed8081b1e ---> e191fcfb8df3 Step 3/7 : COPY . /data/app/flyFish/flyfish ---> b9015d3429f9 Step 4/7 : ENV PATH=/root/.nvm/versions/node/v14.17.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin ---> Running in e900b54d3d64 Removing intermediate container e900b54d3d64 ---> cd0a81c242c1 Step 5/7 : EXPOSE 8364 ---> Running in 459a329058af Removing intermediate container 459a329058af ---> 5e2aeb2eea51 Step 6/7 : RUN sh startup.sh ---> Running in 28b5301ef1d5`

terminal抛出什么异常了吗？
有的话麻烦提供下异常信息~
没有的话还是需要耐心等会，build过程中会有拉取docker基础镜像、前后端项目安装依赖、vscode在线编辑器的安装，安装时间目前在10min左右，这部分我们会逐步优化，减少build过程的安装时间~

**Comment by maxDwq** [comment]
> 使用Docker安装FiyFish v1.0时，在安装组件阶段会因为不明原因消耗较长时间，以下为部分控制台信息，卡顿出现在Pull complete 阶段
> 
> `[root@VM-8-14-centos FlyFish]# docker build -t flyfish . Sending build context to Docker daemon 1.379GB Step 1/7 : FROM luckydwqdocker/flyfish:v1.0 v1.0: Pulling from luckydwqdocker/flyfish 7a0437f04f83: Pull complete 7d9aacdf270e: Pull complete 1449949166f9: Pull complete 939a345cf85c: Pull complete 3a0d0dbd6603: Pull complete Digest: sha256:6322970789d1db9f70d85c62f78bd16a3508a0a7e09cedd9b7fc9a5747457bd2 Status: Downloaded newer image for luckydwqdocker/flyfish:v1.0 ---> 0f47704824ea Step 2/7 : WORKDIR /data/app/flyFish/flyfish ---> Running in 809ed8081b1e Removing intermediate container 809ed8081b1e ---> e191fcfb8df3 Step 3/7 : COPY . /data/app/flyFish/flyfish ---> b9015d3429f9 Step 4/7 : ENV PATH=/root/.nvm/versions/node/v14.17.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin ---> Running in e900b54d3d64 Removing intermediate container e900b54d3d64 ---> cd0a81c242c1 Step 5/7 : EXPOSE 8364 ---> Running in 459a329058af Removing intermediate container 459a329058af ---> 5e2aeb2eea51 Step 6/7 : RUN sh startup.sh ---> Running in 28b5301ef1d5`

![image](https://user-images.githubusercontent.com/36149790/139615491-aebd9a76-dde3-41ae-851f-6b464b6dddbe.png)
成功的案例

**Comment by Tiper-In-Github** [comment]
是的，这个阶段就是出现了卡顿，可以正常向下执行，但是在下一步出现了报错，和这个问题不同，我需要提交一个新的issues吗

**Comment by Tiper-In-Github** [comment]
是的，可以向下继续执行，就是希望可以优化一下这块
