### ISSUE TITLE
是否继续更新

### ISSUE THREAD

**Issue by tanghaojie** [CloudWise-OpenSource/FlyFish#20]

**Comment by ssusieee** [comment]
将会继续更新，敬请期待！具体更新计划，确认后回复于您！

**Comment by ssusieee** [comment]
> _No description provided._
将会继续更新，敬请期待！具体更新计划，确认后回复于您！

**Comment by ssusieee** [comment]
我们计划将于下周更新版本哦，敬请期待！

**Comment by soulferryman** [comment]
FlyFish2.1已于本周更新，详情请见2.1版本release note
