### ISSUE TITLE
导入组件后，组件列表预览图为空

### ISSUE THREAD

**Issue by maxDwq** [CloudWise-OpenSource/FlyFish#32]
![image](https://user-images.githubusercontent.com/36149790/165508696-ff2ceb80-f16d-4e85-b3bf-267e05611f74.png)

**Comment by xiaohu12685** [comment]
暂时只支持编译保存生成缩略图

**Comment by soulferryman** [comment]
@all-contributors please add @xiaohu12685 for Code
