### ISSUE TITLE
组件没有被占用，还是报错是为啥

### ISSUE THREAD

**Issue by maxDwq** [CloudWise-OpenSource/FlyFish#33]
![image](https://user-images.githubusercontent.com/36149790/165510998-6f4e1adb-c9a6-4ecb-bd50-d4605bed403a.png)

**Comment by YouYe** [comment]
应该是依旧有应用在使用组件，可先行筛查一下，FlyFish也再规划之后组件具体被哪些大屏使用的相关功能，敬请期待
