### ISSUE TITLE
大屏下载包是否需要tomcat下访问

### ISSUE THREAD

**Issue by YouYe** [CloudWise-OpenSource/FlyFish#35]
模板我下载下来，里边有个index.html文件，我用浏览器打开，提示加载组件失败，这个是需要部署到tomcat下访问吗，谢谢了
![image](https://user-images.githubusercontent.com/17558799/165659852-15d6f908-ce90-4649-9bd0-de0290b35b1d.png)

**Comment by xiaohu12685** [comment]
是的，找一个Apache或者Nginx进行部署即可
