### ISSUE TITLE
浏览器控制台报错

### ISSUE THREAD

**Issue by jincheny** [CloudWise-OpenSource/FlyFish#39]
### 描述
浏览器控制台有报错，报错原因有多个。

### 复现
登录飞鱼平台，进入组件开发页面。
![image](https://user-images.githubusercontent.com/54785820/165703690-5dd014c7-50d8-4ef2-b360-31577ada62b2.png)

### 环境
环境：社区demo（https://flyfish-demo.opscloudwise.com:23368/）
版本：FlyFish-2.1.0
浏览器：Chrome101.0.4951.41（正式版本） (x86_64)

**Comment by YouYe** [comment]
此issue与[浏览器总有报错](https://github.com/CloudWise-OpenSource/FlyFish/issues/86)重复，关闭当前issue
