### ISSUE TITLE
在设计大屏页面，点击“预览”按钮报错

### ISSUE THREAD

**Issue by ggm99** [CloudWise-OpenSource/FlyFish#4]
![image](https://user-images.githubusercontent.com/73630583/140253699-f6830a6a-d9dd-4db1-b3de-9ed9393a7176.png)
![image](https://user-images.githubusercontent.com/73630583/140253752-208bfb50-558f-4471-9bb4-14dc40762838.png)
去掉链接中的 production 访问正常

**Comment by xiaohu12685** [comment]
已修复，并已合并到main分支。
commit记录为：f35b9a4d4ef15df8d04a3956a4b20e0a10a3a909
