### ISSUE TITLE
建议平台添加版本信息

### ISSUE THREAD

**Issue by jincheny** [CloudWise-OpenSource/FlyFish#40]
飞鱼平台缺乏版本提示信息，用户不知道使用的是哪个版本，可以在侧边栏最下面添加版本号。

![image](https://user-images.githubusercontent.com/54785820/165706268-268780d4-ebcf-4ba0-90c7-1272c10aa2b5.png)

**Comment by YouYe** [comment]
目前不同分支为不同版本的飞鱼，此功能可能被采纳，但最有可能未来会一键安装某个版本的飞鱼，或者在控制台敲version可以查看版本等，在这里可以讨论一下最优的版本解决方案
