### ISSUE TITLE
建议切页增加loading效果

### ISSUE THREAD

**Issue by RiseHao1029** [CloudWise-OpenSource/FlyFish#42]
目前没有loading效果，不够友好

**Comment by RiseHao1029** [comment]
![image](https://user-images.githubusercontent.com/102229441/165725160-b7416eec-c2f5-42c1-b03d-0f79f00dfa52.png)
这片区域

**Comment by xiaohu12685** [comment]
感谢提出此，这是一个好建议，我们将在接下来的版本中加上此功能
