### ISSUE TITLE
组件快照图片不显示

### ISSUE THREAD

**Issue by jincheny** [CloudWise-OpenSource/FlyFish#45]
### 描述
组件开发完成后，组件快照依旧不显示。

### 复现
新建组件，开发组件，上线！
![image](https://user-images.githubusercontent.com/54785820/165890190-e4690b5b-e1e1-460b-b46a-449ce677cee7.png)

**Comment by xiaohu12685** [comment]
需要进行编译一次才可以，进去之后可以在编辑测保存一次将会自动编译

**Comment by soulferryman** [comment]
@all-contributors please add @jincheny  for doc

**Comment by soulferryman** [comment]
@all-contributors please add @lich-y for code
