### ISSUE TITLE
组件源码（含components组件编译后源码）上传失败

### ISSUE THREAD

**Issue by jincheny** [CloudWise-OpenSource/FlyFish#46]
### 描述
导入组件源码（含components组件编译后源码）上传失败，控制台报错413
### 复现
![image](https://user-images.githubusercontent.com/54785820/165890476-c273bf2f-6bee-440b-bdaf-04de35badd4e.png)

**Comment by Neeke** [comment]
413

**Comment by jincheny** [comment]
> 413

已修改，控制台报错提示 413

**Comment by Neeke** [comment]
个性nginx配置可解决。

fixed

**Comment by jincheny** [comment]
nginx 提示报错 413

**问题原因**
nginx 文件上传默认是1MB，飞鱼公共组件大于1M，提示 413 报错且飞鱼组件导入失败。

**解决方案**
服务器根目录下执行以下命令
vim etc/nginx/conf.d/FlyFish-2.1.0.conf

添加配置
![image](https://user-images.githubusercontent.com/54785820/170195078-ee5e3892-3b17-4b53-8de9-90a7bf1adc67.png)

github main分支已修复该Bug。

**Comment by soulferryman** [comment]
@all-contributors please add @Neeke for design
