### ISSUE TITLE
用户角色菜单显示异常问题，多余了很多菜单……

### ISSUE THREAD

**Issue by maxDwq** [CloudWise-OpenSource/FlyFish#48]
<img width="814" alt="image" src="https://user-images.githubusercontent.com/36149790/167241688-0d26cf1e-bce4-49be-b2b4-7fa23b70d04e.png">

**Comment by maxDwq** [comment]
已修复 #47

**Comment by xiaohu12685** [comment]
已修复，版本2.1.1
