### ISSUE TITLE
大屏设计过程中导入json文件报错“文件读取失败”?这个什么原因，有示例吗，谢谢

### ISSUE THREAD

**Issue by hucvicse** [CloudWise-OpenSource/FlyFish#5]
大屏设计过程中导入json文件报错“文件读取失败”?这个什么原因
![1636084559](https://user-images.githubusercontent.com/30923003/140455832-0af7fb8f-9afe-4c07-a891-dc3452bcee0c.jpg)

**Comment by xiaohu12685** [comment]
已修复，并以合并到main分支。
commit记录id为：d8927ae07184cd546457dd841d3bf6f53f8fdb22
