### ISSUE TITLE
飞鱼(FlyFish)组件及模板库能否加入飞鱼(FlyFish)源代码编译自动把组件及模板库编译进系统

### ISSUE THREAD

**Issue by aeaoae** [CloudWise-OpenSource/FlyFish#53]
飞鱼(FlyFish)组件及模板库能否加入飞鱼(FlyFish)源代码编译自动把组件及模板库编译进系统，组件及模板库比较多的话，一个一个导有些麻烦。
飞鱼(FlyFish)组件及模板库
https://github.com/CloudWise-OpenSource/FlyFishComponents

**Comment by xiaohu12685** [comment]
组件不内置在平台之中主要是为了更轻量级的部署，因为不同的场景所需要的组件与应用都是不同的，我们可以根据需要而选择我们的组件与应用。 在下个版本迭代中将会增加批量导入导出，会便捷我们的操作

**Comment by xiaohu12685** [comment]
2.2版本会增加
