### ISSUE TITLE
不知道是不是bug

### ISSUE THREAD

**Issue by RiseHao1029** [CloudWise-OpenSource/FlyFish#59]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。**

![image](https://user-images.githubusercontent.com/102229441/167756035-0083529a-1c33-405d-b3e1-e11ffa8a228c.png)

### 描述 Bug

查看组件diff可以进到一个新的嵌套里面

### 复现 Bug

查看组件记录，点击任意一个记录

## 系统信息

- 浏览器版本:
- 操作系统: CentOS7.6(默认)
- Node 版本: NodeJS14.9(默认)

**Comment by YouYe** [comment]
此功能即将废弃，后续可能在某个版本去除
