### ISSUE TITLE
更新上线的描述可以放大一点

### ISSUE THREAD

**Issue by RiseHao1029** [CloudWise-OpenSource/FlyFish#62]
![image](https://user-images.githubusercontent.com/102229441/167760077-25ba5e85-bf3c-4f22-ade3-41935d6b7848.png)

描述功能

虽然这个输入框支持滚动，但是还是觉得可以放大一点会更好

如果功能与问题有关，请在此处描述您是如何解决问题的

能放大一点这个描述框，因为内容多的时候就不直观了

描述你想要的功能。

**Comment by YouYe** [comment]
感谢您的建议，您是否注意到textArea右下角是可以拖动放大的 ，不过后续我们UE也会针对性对体验进行优化，非常感谢您的建议
