### ISSUE TITLE
组件怎么导入

### ISSUE THREAD

**Issue by YouYe** [CloudWise-OpenSource/FlyFish#77]
组件怎么导入

**Comment by YouYe** [comment]
组件包未导入，组件包下载地址 https://flyfish-demo.opscloudwise.com:23332/commonComponentDownload

**Comment by Rosso-Wang** [comment]
> 组件包未导入，组件包下载地址：https://github.com/CloudWise-OpenSource/FlyFishComponents/tree/main/components
