### ISSUE TITLE
传送门的链接无法访问!

### ISSUE THREAD

**Issue by maxDwq** [CloudWise-OpenSource/FlyFish#82]
### 描述 Bug

三个传送门的链接无法访问,好像都是内网10.开头的IP地址
![image](https://user-images.githubusercontent.com/36149790/167838293-8a89d4c4-18f9-46aa-9587-748b1d7c5c0e.png)

### 复现 Bug

必现

## 系统信息

- 浏览器版本: 
![image](https://user-images.githubusercontent.com/36149790/167838391-906bb6a6-f862-484a-b835-38d4cac5fd9f.png)
- 操作系统: CentOS7.6(默认)
- Node 版本: NodeJS12.22(默认)

**Comment by maxDwq** [comment]
此页面无意义，预计4月8号之前移除掉

**Comment by maxDwq** [comment]
此页面无意义，预计4月8号之前移除掉

**Comment by soulferryman** [comment]
@all-contributors please add @maxDwq  for review
