### ISSUE TITLE
组件开发列表总有一些报错

### ISSUE THREAD

**Issue by RiseHao1029** [CloudWise-OpenSource/FlyFish#86]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。**

![image](https://user-images.githubusercontent.com/102229441/167842342-51617ffb-5d72-4e2f-8c58-e92b6c0adef9.png)

### 描述 Bug

打开组件开发页面，刷新列表可以看到一些报错信息

### 复现 Bug

打开组件开发页面，打开F12，刷新浏览器

## 系统信息

- 浏览器版本:
- 操作系统: CentOS7.6(默认)
- Node 版本: NodeJS14.9(默认)

**Comment by YouYe** [comment]
确认为bug，不影响当前使用，将在未来版本修复，修复版本确认之前，此issue不会关闭

**Comment by soulferryman** [comment]
@all-contributors please add @aiwhj for audio
