### ISSUE TITLE
在大屏开发页面，组件预览图无法显示

### ISSUE THREAD

**Issue by jincheny** [CloudWise-OpenSource/FlyFish#90]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。**

- [x] 已阅读 [开发文档](http://docs.aiops.cloudwise.com/zh/flyfish/)、[01-基础环境准备篇](../../doc/01-%E5%9F%BA%E7%A1%80%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87%E7%AF%87.md)、[02-FlyFish 平台部署篇](../../doc/02-FlyFish%E5%B9%B3%E5%8F%B0%E9%83%A8%E7%BD%B2%E7%AF%87.md)、[03-code_server 部署篇](../../doc/03-code_server%E9%83%A8%E7%BD%B2%E7%AF%87.md)。
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现。
- [x] 已在 Issues 中搜索了相关的关键词

### 描述 Bug

<img width="227" alt="截屏2022-05-10 下午11 46 28" src="https://user-images.githubusercontent.com/54785820/167846011-523269e5-dd69-4a4b-94d8-107184ad07f8.png">

### 复现 Bug

成功上线组件 —— 应用开发 —— 基础组件加载完毕

## 系统信息

- 浏览器版本: Chrome 101.0.4951.54（正式版本） (x86_64)
- 操作系统: CentOS7.6(默认)
- Node 版本: NodeJS14.9(默认)

**Comment by xiaohu12685** [comment]
暂时需要进入组件中编译才可生成缩略图

**Comment by xiaohu12685** [comment]
看到ip、port没有，请检查lcapWww/web/screen/config/env.js文件，的apiDomain是否指向争取的地址

apiDomain要指向组件的www目录

**Comment by xiaohu12685** [comment]
看到ip、port没有，请检查lcapWww/web/screen/config/env.js文件的apiDomain是否指向正确的地址

apiDomain要指向组件的www目录

**Comment by jincheny** [comment]
@xiaohu12685 Great！问题解决了。

部署文档同步修改步骤。
自动化部署脚本中也加入了此处修改内容。
![image](https://user-images.githubusercontent.com/54785820/170994040-3b9511e1-4a6a-4da9-b244-d626711db6e7.png)

**Comment by xiaohu12685** [comment]
赞，👍
