### ISSUE TITLE
重启虚拟机后，飞鱼平台无法访问，页面提示404 Not Found

### ISSUE THREAD

**Issue by jincheny** [CloudWise-OpenSource/FlyFish#91]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。**

- [x] 已阅读 [开发文档](http://docs.aiops.cloudwise.com/zh/flyfish/)、[01-基础环境准备篇](../../doc/01-%E5%9F%BA%E7%A1%80%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87%E7%AF%87.md)、[02-FlyFish 平台部署篇](../../doc/02-FlyFish%E5%B9%B3%E5%8F%B0%E9%83%A8%E7%BD%B2%E7%AF%87.md)、[03-code_server 部署篇](../../doc/03-code_server%E9%83%A8%E7%BD%B2%E7%AF%87.md)。
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现。
- [x] 已在 Issues 中搜索了相关的关键词

### 描述 Bug

![WechatIMG537](https://user-images.githubusercontent.com/54785820/167848785-de2e884b-46a6-492a-a670-41cd890de25a.png)

### 复现 Bug

重启虚拟机，清除浏览器缓存、以及cookie，访问飞鱼平台。

## 系统信息

- 浏览器版本: Chrome 101.0.4951.54（正式版本） (x86_64)
- 操作系统: CentOS7.6(默认)
- Node 版本: NodeJS14.9(默认)

**Comment by YouYe** [comment]
重启虚拟机 请先确认服务是否正确启动了 可以配置虚拟机开机自动拉起服务，如正常启动 需要进一步排查问题了

**Comment by jincheny** [comment]
@YouYe 问题已解决！

**问题原因：**
mongodb数据库自动重启失败导致，登录FlyFish后提示 404 Not Found。

**解决方案：**
![image](https://user-images.githubusercontent.com/54785820/170180951-da44ba63-e90e-4dc0-aeb5-2dec44e2f9c8.png)

**虚拟机重启，FlyFish平台重启完整步骤以及数据库重启失败解决方案：**
https://www.toutiao.com/article/7097480448284230182/?log_from=3326a31e96705_1653453249488

**Comment by soulferryman** [comment]
@all-contributors please add @lich-y for code

**Comment by soulferryman** [comment]
@all-contributors  please  add @lich-y  for code

**Comment by soulferryman** [comment]
@all-contributors please add @ayongv for doc
