### ISSUE TITLE
一键安装成功后，开发组件发现code-server模块图标都没有显示！

### ISSUE THREAD

**Issue by jincheny** [CloudWise-OpenSource/FlyFish#92]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。**

- [x] 已阅读 [开发文档](http://docs.aiops.cloudwise.com/zh/flyfish/)、[01-基础环境准备篇](../../doc/01-%E5%9F%BA%E7%A1%80%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87%E7%AF%87.md)、[02-FlyFish 平台部署篇](../../doc/02-FlyFish%E5%B9%B3%E5%8F%B0%E9%83%A8%E7%BD%B2%E7%AF%87.md)、[03-code_server 部署篇](../../doc/03-code_server%E9%83%A8%E7%BD%B2%E7%AF%87.md)。
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现。
- [x] 已在 Issues 中搜索了相关的关键词

### 描述 Bug

<img width="1029" alt="截屏2022-04-29 下午2 09 56" src="https://user-images.githubusercontent.com/54785820/167851465-e546a6fd-40f7-4ee9-a6f7-d2bf42460d66.png">

### 复现 Bug

一键安装 —— 开发组件

## 系统信息

- 浏览器版本: Chrome 101.0.4951.54（正式版本） (x86_64)
- 操作系统: CentOS7.6(默认)
- Node 版本: NodeJS14.9(默认)

**Comment by YouYe** [comment]
审查一下元素，看未加载的icon是否是未请求到，未请求到原因可能是某些配置不适配当前环境，可以截图一下，再进一步确认原因

**Comment by jincheny** [comment]
@YouYe code-server 显示正常了

**问题原因**
并没有做特别仔细的排查，只是后面在使用FlyFish的时候正常了。可能是首次加载code-server时由于网络原因等问题导致icon没有请求到，后续发现问题再同步到该issue下。
